### ISSUE TITLE
Is the project maintained?

### ISSUE THREAD

**Issue by vladfaust** [mccallofthewild/markov#1]
Hello,

I've checked your project and it's failing to build (or the specs failed) with the latest Crystal (0.26.1) or there are no any specs so the project cannot be validated to be up to date. Your project is in [Awesome Crystal](https://github.com/veelenga/awesome-crystal) list, so I'd like to ask if the project maintained?

I'll initiate a PR to remove your project from the list if you don't respond positively within 7 days.

I'm sorry if I'm wrong, because I've been checking many shards with automated script.

Thanks,
Vlad.

**Comment by mccallofthewild** [comment]
Thank you for bringing this to my attention. The issue has been resolved in [v0.1.2](https://github.com/mccallofthewild/markov/releases/tag/v0.1.2).

**Comment by vladfaust** [comment]
Note that you can set up daily/weekly tests on Travis so you'll receive a notification when the build begins to fail: https://docs.travis-ci.com/user/cron-jobs.

Thanks.

**Comment by mccallofthewild** [comment]
Thanks for the tip! Cron job Travis builds are now active on both [Markov](https://github.com/mccallofthewild/markov) and [GDAX](https://github.com/mccallofthewild/gdax).
